### ISSUE TITLE
Wow API Import fails for two users from different realms in the same guild.

### ISSUE THREAD

**Issue by AJH16** [bbDKP/bbDKP#249]
The filtering for usernames in the wow armory importer does not work for multiple characters with the same name but on different realms in the same guild.  This is due to incorrect filtering on only character name and guild.  It should instead be on character name, realm and guild.  The easiest fix for this is in the Member's class to add a hyphen and the realm name to both the newmembers and oldmembers arrays and then update the membership checks in the intersection and diff to use the same system.  Additionally, the query of members from the DB needs to pull the realm.

Additionally, changes must be made to the Db schema as the unique constraint on the memberlist table is invalid.  It should have the realm added to the unique constraint.

Finally, the makemember exists check must be updated to filter on realm as well or it will still not add the new member.

I can submit a patch if I can get access to submit as well.

**Comment by Sajaki** [comment]
seems to be fixed now
