### ISSUE TITLE
UCP & Roles.php

### ISSUE THREAD

**Issue by spitefultowel** [bbDKP/bbDKP#256]
UCP bbDKP 1.4 makes a lot of references to includes/bbDKP/controller/guilds/Roles.php which doesn't exist. This prevents characters from being imported manually.

2015/01/23 14:46:14 [error] 62234#0: *156 FastCGI sent in stderr: "PHP message: PHP Fatal error:  require(): Failed opening required './includes/bbdkp/controller/guilds/Roles.php' (include_path='.:/usr/share/php:/usr/share/pear') in /usr/share/nginx/spitefultowel.com/rho/includes/ucp/ucp_dkp.php on line 27" while reading response header from upstream, client: 104.51.211.246, server: rho.spitefultowel.com, request: "GET /ucp.php?i=232 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "guild.website.com.com", referrer: "https://guild.website.com/ucp.php"

**Comment by spitefultowel** [comment]
2015/01/23 14:50:14 [error] 62234#0: *165 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'bbdkp\controller\guilds\Roles' not found in /usr/share/nginx/spitefultowel.com/rho/includes/ucp/ucp_dkp.php on line 531" while reading response header from upstream, client: 104.51.211.246, server: rho.spitefultowel.com, request: "GET /ucp.php?i=dkp&mode=characteradd HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "guild.website.com", referrer: "https://guild.website.com/ucp.php?i=232"

**Comment by Sajaki** [comment]
fixed in be0c34b5a23a7586e8e0b9f913767aa817f85bc2
